### PR TITLE
Add Bounds and ArrayRange metadata

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by willdunklin** [comment]
This seems to resolve the failures I was having with my local testing. Thanks for the quick turnaround on this!

**Review by willdunklin — APPROVED** [review]

**Comment by danlipsa** [comment]
Great! @burlen Lets merge this. Thanks!

**Comment by burlen** [comment]
@danlipsa looks good! Thanks for tackling this so quickly. I think you have merge permission. Would you please give it a try an let me know if not?

**Comment by danlipsa** [comment]
It tells me I am not authorized to merge this.

**Comment by danlipsa** [comment]
This is the message printed under "merging is blocked"
The base branch restricts merging to authorized users. [Learn more about protected branches.](https://docs.github.com/articles/about-protected-branches/)

**Comment by burlen** [comment]
@danlipsa ok, seems like the branch protection setting is too restrictive. I tried to loosen it up. Hope this solves the issue.

**Pull request merged**
