### PR TITLE
WIP - curation

### PR DESCRIPTION
**Pull request by burlen**
@patrickoleary @ghweber @srizzi88 @mvictoras @c-wetterer-nelson @patrickoleary 

The team can add to Corey's work here. Pushes to this branch will trigger a read the docs build and can be viewed here
https://sensei-insitu.readthedocs.io/en/curation-vignettes/

When editing the rtd sources follow the style and conventions used elsewhere in the document. These are documented here:
https://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html

Before pushing check that your work compiles and renders in html. To do so cd into the `rtd-docs` dir and type `make -j html` once the page is built open it in Firefox to see how it looks with `firefox _build/html/index.html`. Issues that you might encounter include not having sphinx installed, this is done with pip, google can help.

### CODE REVIEW

**Comment by burlen** [comment]
@c-wetterer-nelson This is the PR that results in trigger to rtd. However, I do not see your new pages on the RTD site. Did you include them in the main document somewhere?  If not can you please do so and verify that they show up at the RTD site? Link is above

**Comment by burlen** [comment]
please make use of conventions here
https://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html

**Comment by srizzi88** [comment]
@burlen I added additional contents. Please merge.

**Comment by burlen** [comment]
@srizzi88 thank you! this should be rebased before merge.

**Pull request merged**
