### PR TITLE
WIP: Catalyst2 analysis and data adaptors

### PR DESCRIPTION
**Pull request by CharlesGueunet**
Add Catalyst 2 Data adaptor (conduit based, but using the vtkConduitSource) and the corresponding Analysis adaptor (in progress)

### CODE REVIEW

**Comment by burlen** [comment]
@CharlesGueunet looks great. Are you ready to merge? If not, just ping us when you are.

**Comment by CharlesGueunet** [comment]
Not ready yet, I will tag you once this work is finished and tested :)

**Comment by CharlesGueunet** [comment]
@burlen this is starting to work on my side, I was able to have a catalyst pipeline and a live visu on unstructured meshes using Catalyst 2. However, in the `Catalyst2AnalysisAdaptor` I cast the internal **dataAdaptor** to d `Catalyst2DataAdaptor`. I feel this is not optimal, but it allows me to retrieve the internal conduit nodes directly without transforming my data inta a VTK Object back and forth. What would be the drawback of such a cast ?

**Comment by burlen** [comment]
@CharlesGueunet you'll need to use the base class, sensei::DataAdaptor, directly. This is because the caller can be any simulation, not just yours. Heads up,  sensei 4 will use a mangled VTK to avoid version conflicts with dependencies such as ParaView and VisIt. Another change is integration of Utkarsh's bi-directional work. These should be easy changes for you, just wanted to mention. See #3

**Comment by CharlesGueunet** [comment]
My main problem is that using the DataAdaptor API, I cannot forward the internal conduit node to catalyst 2 directly, I need to transform the node to a VTK Object via GetMesh and come back to a conduit node. This is error prone and leads to memory issue as Conduit is SoA internally and VTK miss the required method to get SoA datat (the vtkSoAGenericDatatArray::GetVoidPointer makes a deep copy). 
I do not see how the caller can requires a Catalyst2 pipeline without using a Catalyst2 adaptor, can you give me an example ?

> Another change is integration of Utkarsh's bi-directional work.

Are you talking about the steering ? or about the VTK <-> Conduit translation ?

> These should be easy changes for you, just wanted to mention

Our solution if we are foced to use the intermediate VTK Object is to move the `vtkConduitSource` and `vtkDataObjectToConduit` from VTK to ParaView so we can use them. This is a much longer task and I think the result will be less robust.

Thank you for your help.

**Comment by CharlesGueunet** [comment]
> The cost of generic in situ is going through the data model. It's more work but the trade off is that simulations can code to a single data model and in situ interface.

Does that mean that we should be able to use a CatalystDataAdaptor with a Catalyst2AnalysisAdaptor ? Would it make sens to resptrict the Catalyst2AnalysisAdaptor to work with conduit based data adaptor at least in a first step ?

> I have no love for the VTK data model, and there certainly are some issues with it. however, one can indeed do zero-copy through VTK. VTK's `GetPointer` (best option) or `GetVoidVoidPointer` (not type safe) will only make a copy _if the underlying data is not in the contiguous layout_. The way to ensure that these API do not make a copy is to detect the layout by down casting to either the AOS or the SOA, and then use the specialized get pointer API. Here is an example:
> 
> ```c++
>    switch (da->GetDataType())
>    {
> ...
>    }
> ```
> 
> This will code will never result in a deep copy.

Thank you for this snippet, but I do not want to deal with the data translation myself. I will rely on the `vtkConduitSource` and `vtkDataObjectToConduit` instead. We just need to move them to VTK first as they are still on ParaView.

**Comment by burlen** [comment]
> Does that mean that we should be able to use a CatalystDataAdaptor with a Catalyst2AnalysisAdaptor ? 

It means that in SENSEI all analysis adaptors code to the `sensei::DataAdaptor`, and not to any specialized derived data adaptors. In this way simulations can access any/all of the back ends without any dependence on a specific back end. What you're suggesting would require a simulation to use the Catalyst specific data adaptor, and this would introduce a dependence on Catalyst for those not using Catalyst. It would also mean that to access any of the other back ends the simulation would need a second data adaptor since none of the other back ends will code to your Catalyst adaptor. This approach ruins generality that is the main idea behind SENSEI.

> Would it make sens to resptrict the Catalyst2AnalysisAdaptor to work with conduit based data adaptor at least in a first step ?

Sure, but this could not become part of the SENSEI code base.

> I will rely on the vtkConduitSource and vtkDataObjectToConduit instead. 

I'm unsure of what the details of this are, but if it is the case that these vtk filters do a bulk conversion of some conduit tree to a vtk data object, then this likely is an fairly inefficient way to go. The reason is that SENSEI is "demand driven", meaning an analysis will only request the data that it needs. A bulk conversion short circuits that and usually results in more work being done that is necessary.

I appreciate your work, and am sorry to be the bearer of bad news.

**Comment by CharlesGueunet** [comment]
> It means that in SENSEI all analysis adaptors code to the `sensei::DataAdaptor`, and not to any specialized derived data adaptors. In this way simulations can access any/all of the back ends without any dependence on a specific back end. What you're suggesting would require a simulation to use the Catalyst specific data adaptor, and this would introduce a dependence on Catalyst for those not using Catalyst. It would also mean that to access any of the other back ends the simulation would need a second data adaptor since none of the other back ends will code to your Catalyst adaptor. This approach ruins generality that is the main idea behind SENSEI.

This completely make sense, I understand.

> I'm unsure of what the details of this are, but if it is the case that these vtk filters do a bulk conversion of some conduit tree to a vtk data object, then this likely is an fairly inefficient way to go. The reason is that SENSEI is "demand driven", meaning an analysis will only request the data that it needs. A bulk conversion short circuits that and usually results in more work being done that is necessary.

These filters should work in 0-copy (even if it is not always true as the SoA / AoS incompatibility may trigger some copy, but this is more a bug that need to be fixed than a design). So they may be bulk conversion but they normally should nod trigger a lot of work.

I have tried to take inspiration from the alreasy existing ConduitDataAdaptor to see if I could add a similar Catalyst 2 data adaptor. Unfortunately, Catalyst 2 only has a subset of conduit which make this work really hard. For example, I found no way to have:
* conduit::int_array / double_array ...
* the corresponding translation methods
* Node::value() and the conduit::DataArray<>
* Node::to_json_default

Is there a way to wrap an existing conduit node into the specific Catalyst2 implementation ?
I would like to be able to extend the functionality of Catalyst2 Conduit or to make a more complete adapter, unfortunately I have limited time on this.

> I appreciate your work, and am sorry to be the bearer of bad news.

No problem, you make what is required to keep this project clean and working, I understand :)

**Comment by danlipsa** [comment]
Development moved at
https://github.com/danlipsa/SENSEI/tree/Catalyst2

**Pull request closed without merging**
