### PR TITLE
Add particles metadata

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@burlen @patrickoleary @c-wetterer-nelson Please review

**Comment by danlipsa** [comment]
@burlen Something wrong with the fedora35 ci?

**Comment by danlipsa** [comment]
Can I run all the tests on my local machine?

**Review by burlen — APPROVED** [review]

**Comment by burlen** [comment]
@danlipsa not sure what's up with the spack builds, but we have seen that before. I'm confident it is not related to your work here. if anything rebase from latest develop (if it is out of date) before merging.

**Comment by danlipsa** [comment]
Thanks @burlen . Can you merge as well. I don't have merge permission. Thanks!

**Comment by danlipsa** [comment]
Can you post a link of the failures?

**Comment by burlen** [comment]
The metadata has some issues after the change. Those tests only run if you compile sensei with vtk support.

**Comment by danlipsa** [comment]
Does this fix it? 
https://github.com/SENSEI-insitu/SENSEI/pull/131

**Comment by willdunklin** [comment]
Yep that looks good to me

**Pull request merged**
