### PR TITLE
Warning when analysis/transport is not enabled

### PR DESCRIPTION
**Pull request by jwindgassen**
For clearer Feedback to the user, they should be informed when an analysis/transport in the XML is not enabled. As currently, it will be silently dropped and ignored.

I decided to use `SENSEI_WARNING`, but using `SENSEI_STATUS` would also be possible here if that is too verbose. 

I would also argue, that it would be more intuitive, if the default value of the `enabled` attribute is `true`, but decided to leave it be for now.

### CODE REVIEW

**Comment by jwindgassen** [comment]
I think the best way would be either:
- Issue a *warning* when assuming analyses are *disabled* by default, or
- Issue an *info* when analyses are assumed to be *enabled* by default (because a user has to explicitly disable it)

**Comment by burlen** [comment]
we took the opposite approach to report when an analysis was enabled. meaning if you don't see a report that you expected you know it was skipped. However, I'll merge this if you change warning to a status report.

**Comment by burlen** [comment]
also, having things default to enabled makes sense to me.

**Comment by burlen** [comment]
@jwindgassen thank you!

**Pull request merged**
